name: test-actions

run-name: ${{ github.actor }} is testing Github test-actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t test-image -f Dockerfile.dev .
      - run: docker run test-image npm run test
